
import os,sys, ast, tomllib, argparse, subprocess, datetime, traceback

user_sbxes_path = None
def main():
    global user_sbxes_path
    arg_parser = argparse.ArgumentParser( add_help=True,
        description="The Deploy Tool of Tree Sandbox"
    )
    arg_parser.add_argument("-s", default=None, metavar='<dir>',
                            help="The path of the dir that contains your list.toml and uc.<name>.py files. Defaultly use the same dir as this deploy tool script file.")

    (known_args, # 上面列出的参数
        user_cli_argv # 未知参数，即之后的参数，传给沙箱内的app
    ) = arg_parser.parse_known_args()
    user_sbxes_path = known_args.s
    if not user_sbxes_path: user_sbxes_path = scriptdirpath

    log(f"Using python interpreter << '{sys.executable}' >> . This interpreter will also be used in deployed specific-sandbox startup .py files.")
    log(f"Look for user custom list.toml and uc.<name>.py files in '{user_sbxes_path}'")
    log('')

    list_file = f'{user_sbxes_path}/list.toml'
    try:
        my_sandboxes = d(tomllib.loads(open(list_file).read() ) ).my_sandboxes
    except Exception as err:
        log_warn(f'Failed to read and parse {list_file}')
        log_warn(err)
        sys.exit(1)
    for sbx in my_sandboxes:
        # log(sbx)
        try:
            deploy_one_sandbox(sbx)
        except Exception as err:
            log_warn(f'✘ Error occured when distributing sandbox {sbx}: {err}')
            traceback.print_exc()


def deploy_one_sandbox(sbx):
    if sbx.destfile:
        destfile = sbx.destfile
        if not destfile.lower().endswith('.py'):
            raise Exception("destfile should end with '.py'")
    elif sbx.destdir:
        destfile = f'{sbx.destdir}/tsbxrun_{sbx.name}.py'
    else:
        raise Exception("No destdir nor destfile")

    uc_filename = f'uc.{sbx.name}.py'
    uc_file_path = f'{user_sbxes_path}/{uc_filename}'
    if not os.path.exists(uc_file_path):
        log_warn(f'✘ User config file not exist {uc_file_path} . Skip {sbx}')
        return False
    if not check_pyfile_syntax(uc_file_path):
        log_warn(f'✘ Syntax error in file {uc_file_path}. Skip {sbx}')
        return False

    destdir = os.path.dirname(destfile)
    if not os.path.exists(destdir):
        log(f'Dir {destdir} not exist. Skip {sbx}.')
        return False

    if os.path.exists(destfile) and os.stat(destfile).st_size > 0:
        if not 'Tree Sandbox' in open(destfile).read(800):
            log_warn(f'✘ Target file {destfile} already exists and its content seems not to be a script of Tree Sandbox. Skip {sbx} . Please manually check and remove it if needed.')
            return False

    tsver = sbx.tsver
    if not tsver:
        verstring = 'file-as-is'
    else:
        verstring = tsver

    progcodeinfo = get_progcodeinfo_by_ver(verstring)
    if progcodeinfo == 'preholder':
        raise Exception(f'Encountered some problem with program code in {verstring}')


    onesbx_code_content = make_onesbx_code(uc_file_path, progcodeinfo )

    with open(destfile, 'w') as f:
        f.write(onesbx_code_content)
        os.chmod(f.name, 0o755)
    log(f'Write to {destfile} done.')

def make_onesbx_code(uc_file_path, progcodeinfo):
    uc_file_content = open(uc_file_path).read()

    full_code = f'''#!/usr/bin/env -S {sys.executable} -IBS

# Version of TreeSandbox program code: {progcodeinfo.tsver_tip}

{progcodeinfo.code_beforeUc}

# !! NOTE Do NOT modify this file here. This file is auto generated by deploy script of TreeSandbox. The uc.<name>.py config file is the userconfig source. !!


{uc_file_content}
{progcodeinfo.code_afterUc}
    '''
    return full_code


Codes = None
def get_progcodeinfo_by_ver(verstring):
    global Codes

    if Codes is None:
        Codes = d()

    if Codes[verstring]:
        return Codes[verstring]

    Codes[verstring] = 'preholder'

    if verstring == 'file-as-is' :
        ts_prog_file = f'{scriptpadirpath}/treesandbox.py'
        timestamp_disp = datetime.datetime.fromtimestamp(os.stat(ts_prog_file).st_mtime) \
            .strftime("%Y-%m-%d %H:%M:%S")
        tsver_tip = timestamp_disp
        orig_code_content = open(ts_prog_file).read()
    elif verstring.startswith('git:tag:'):
        tagname = verstring.removeprefix('git:tag:')
        tsver_tip = f'git tag {tagname}'
        orig_code_content = run_cmd_get_stdout(['git', 'show', f'refs/tags/{tagname}:treesandbox.py'])
    elif verstring.startswith('git:commit:'):
        commit = verstring.removeprefix('git:commit:')
        tsver_tip = f'git commit {commit}'
        orig_code_content = run_cmd_get_stdout(['git', 'show', f'{commit}:treesandbox.py'])
    else:
        raise Exception(f'Invalid version string {verstring}')

    try:
        split_result = split_origcode(orig_code_content)
    except:
        log_warn(f'Failed to split {verstring} original program code into head and body parts')
        raise

    if not check_pycode_syntax(split_result.code_beforeUc):
        raise Exception(f'Syntax error detected in the head of treesandbox.py')
    if not check_pycode_syntax(split_result.code_afterUc):
        raise Exception(f'Syntax error detected in the body of treesandbox.py')

    result = D(
        tsver_tip = tsver_tip,
        code_beforeUc = split_result.code_beforeUc,
        code_afterUc = split_result.code_afterUc,
        lineofs_af = split_result.lineofs_af,
    )
    Codes[verstring] = result
    return Codes[verstring]


def run_cmd_get_stdout(cmdvec):
    proc = subprocess.Popen( cmdvec,
        stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        raise Exception(f'Error when executing command {cmdvec} . Stderr: {stderr.decode()}')
    return stdout.decode()





def split_origcode(origcode ):
    TSBXS_LINES = origcode.splitlines()

    start_marker = "# === USER_CONFIG BEGIN ==="
    end_marker =   "# === USER_CONFIG END ==="

    start_index = None
    end_index = None

    for i, line in enumerate(TSBXS_LINES):
        if line.startswith(start_marker):
            start_index = i
        elif line.startswith(end_marker):
            end_index = i
        if start_index is not None and end_index is not None:
            break
    if start_index is None:
        raise Exception(f"✘ Failed find start mark '{start_marker}'")
    if end_index is None:
        raise Exception(f"✘ Failed find end mark '{end_marker}'")
    if not (start_index < end_index):
        raise Exception(f'✘ Start mark and end mark have wrong sequence')

    code_beforeUc = '\n'.join( TSBXS_LINES[:start_index+1] )
    code_afterUc = '\n'.join( TSBXS_LINES[end_index:] )

    result = D(
        code_beforeUc = code_beforeUc,
        code_afterUc = code_afterUc,
        lineofs_af = end_index,
    )
    return result





def check_pyfile_syntax(filepath):
    try:
        ast.parse(open(filepath).read())
        return True
    except SyntaxError as e:
        print(f"❌ Syntax Error in {filepath}:")
        print(f"   Line {e.lineno}, Col {e.offset}: \n{e.text if e.text else ''}")
        print(f"   Err msg: {e.msg}")
        return False

def check_pycode_syntax(codecontent):
    try:
        ast.parse(codecontent)
        return True
    except SyntaxError as e:
        print(f"❌ Syntax Error:")
        print(f"   Line {e.lineno}, Col {e.offset}: \n{e.text if e.text else ''}")
        print(f"   Err msg: {e.msg}")
        return False



# ================================================

loghead = ''
def set_loghead(new_loghead):
    global loghead
    loghead = new_loghead.rstrip(': ') + ': '
    sys.excepthook = custom_excepthook
def log(*args, **kwargs):
    new_args = args
    if loghead: new_args = ( loghead,  *args)
    print(*new_args, **kwargs)
def log_warn(*args, **kwargs):
    if 'file' not in kwargs: kwargs['file'] = sys.stderr
    log('WARNING ✘: ',  *args, **kwargs)


class EnhancedFalse:
    def __init__(self, dictObj, keyName):
        self.dictObj = dictObj
        self.keyName = keyName
    def _error(self):
        raise Exception(f"✘ Program tries to stringlize or compare a non-defined member '{self.keyName}' of a dict-like obj: {str(self.dictObj)[:200]} ...")
    def __str__(self):
        self._error()
    def __repr__(self):
        self._error()
    def __bool__(self):
        return False
    def __eq__(self, other):
        return False
    def __ne__(self, other):
        return True
    def __lt__(self, other):
        self._error()
    def __le__(self, other):
        self._error()
    def __gt__(self, other):
        self._error()
    def __ge__(self, other):
        self._error()
    __hash__ = None


class EnhancedDictTempl(dict):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, value in self.items():
            if isinstance(value, dict) and not isinstance(value, type(self)):
                self[key] = type(self)(value)
            elif isinstance(value, list):
                self[key] = self._convert_list(value)
    def _convert_list(self, lst):
        new_list = []
        for item in lst:
            if isinstance(item, dict) and not isinstance(item, type(self)):
                new_list.append(type(self)(item))
            elif isinstance(item, list):
                new_list.append(self._convert_list(item))
            else: new_list.append(item)
        return new_list
    def __setattr__(self, name, value):
        self[name] = value
    def __delattr__(self, name):
        try: del self[name]
        except KeyError: pass
    def __setitem__(self, key, value):
        processed_value = value
        if isinstance(value, dict) and not isinstance(value, type(self)):
            processed_value = type(self)(value)
        elif isinstance(value, list):
             processed_value = self._convert_list(value)
        super().__setitem__(key, processed_value)
class Dict(EnhancedDictTempl):
    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)
        try: return self[name]
        except :
            raise
class DictFALSE(EnhancedDictTempl):
    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"): raise AttributeError(name)
        try: return self[name]
        except KeyError:
            return EnhancedFalse(self, name)
    def __getitem__(self, key):
        try: return super().__getitem__(key)
        except KeyError:
            return EnhancedFalse(self, key)
class DictNone(EnhancedDictTempl):
    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)
        try: return self[name]
        except :
            return None
    def __getitem__(self, key):
        try: return super().__getitem__(key)
        except KeyError:
            return None
D = Dict  # Raises an error when trying to access a non-existent key.
d = DictFALSE  # Returns EnhancedFalse when trying to access a non-existent key.
dn = DictNone  # Returns None when trying to access a non-existent key.


# ================================================

scriptfilepath = os.path.abspath(__file__)
scriptdirpath = os.path.dirname(scriptfilepath)
scriptpadirpath = os.path.dirname(scriptdirpath)


main()
