
import os,sys, ast, tomllib

def main():
    log(f'Using python interpreter << {sys.executable} >> . This interpreter will also be used in distributed .py files.')

    my_sandboxes = d(tomllib.loads(open(f'{scriptdirpath}/list.toml').read() ) ).my_sandboxes
    prepare()
    for sbx in my_sandboxes:
        # log(sbx)
        try:
            distribute_sandbox(sbx)
        except Exception as err:
            log_warn(f'Error occured when distributing sandbox {sbx}: {err}')


def distribute_sandbox(sbx):
    if sbx.distfile:
        distfile = sbx.distfile
    else:
        distfile = f'{sbx.distdir}/tsbxrun_{sbx.name}.py'

    uc_filename = f'uc.{sbx.name}.py'
    uc_file_path = f'{scriptdirpath}/{uc_filename}'
    if not os.path.exists(uc_file_path):
        log_warn(f'User config file not exist {uc_file_path} . Skip {sbx}')
    if not check_pyfile_syntax(uc_file_path):
        log_warn(f'Syntax error in file {uc_file_path}. Skip {sbx}')
        return False

    distdir = os.path.dirname(distfile)
    if not os.path.exists(distdir):
        log(f'Dir {distdir} not exist. Skip {sbx}.')

    if os.path.exists(distfile) and os.stat(distfile).st_size > 0:
        if not 'Tree Sandbox' in open(distfile).read(800):
            log_warn(f'Target file {distfile} already exists and its content seems not to be a script of Tree Sandbox. Skip {sbx} . Please manually check and remove it if needed.')
            return False

    code_content = make_tsbx_code(uc_file_path)

    with open(distfile, 'w') as f:
        f.write(code_content)
        os.chmod(f.name, 0o755)
    log(f'Write to {distfile} done.')

def make_tsbx_code(uc_file_path):
    uc_file_content = open(uc_file_path).read()

    full_code = f'''#!/usr/bin/env -S {sys.executable} -IBS
{BEFORE}

# !! NOTE Do NOT modify this file here. This file is auto generated by deploy script of TreeSandbox. The uc.<name>.py config file is the userconfig source. !!

{uc_file_content}
{AFTER}
    '''
    return full_code

BEFORE = None
AFTER = None
def prepare():
    global BEFORE, AFTER
    TSBX_ORIG_CODE_FILEPATH = f'{scriptpadirpath}/treesandbox.py'
    TSBX_ORIG_CONTENT = open(TSBX_ORIG_CODE_FILEPATH).read()
    TSBXS_LINES = TSBX_ORIG_CONTENT.splitlines()

    start_marker = "# === USER_CONFIG BEGIN ==="
    end_marker =   "# === USER_CONFIG END ==="

    start_index = None
    end_index = None

    for i, line in enumerate(TSBXS_LINES):
        if line.startswith(start_marker):
            start_index = i
        elif line.startswith(end_marker):
            end_index = i
        if start_index is not None and end_index is not None:
            break
    if start_index is None:
        low_warn(f"Failed find start mark '{start_marker}' in {TSBX_ORIG_CODE_FILEPATH}")
        sys.exit(1)
    if end_index is None:
        low_warn(f"Failed find end mark '{end_marker}' in {TSBX_ORIG_CODE_FILEPATH}")
        sys.exit(1)
    if not (start_index < end_index):
        log_warn(f'Start mark and end mark have wrong sequence in {TSBX_ORIG_CODE_FILEPATH}')
        sys.exit(1)

    BEFORE = '\n'.join( TSBXS_LINES[:start_index+1] )
    AFTER = '\n'.join( TSBXS_LINES[end_index:] )
    AFTER = '\n\n' + TSBXS_LINES[end_index] + '\n\n' + ast.unparse(ast.parse(AFTER))

    if not check_pycode_syntax(BEFORE):
        log_warn('Syntax error detected in the head of treesandbox.py')
        sys.exit(1)
    if not check_pycode_syntax(AFTER):
        log_warn('Syntax error detected in the body of treesandbox.py')
        sys.exit(1)


def check_pyfile_syntax(filepath):
    try:
        ast.parse(open(filepath).read())
        return True
    except SyntaxError as e:
        print(f"❌ Syntax Error in {filepath}:")
        print(f"   Line {e.lineno}, Col {e.offset}: {e.text.strip() if e.text else ''}")
        print(f"   Err msg: {e.msg}")
        return False

def check_pycode_syntax(codecontent):
    try:
        ast.parse(codecontent)
        return True
    except SyntaxError as e:
        print(f"❌ Syntax Error:")
        print(f"   Line {e.lineno}, Col {e.offset}: {e.text.strip() if e.text else ''}")
        print(f"   Err msg: {e.msg}")
        return False



# ================================================

loghead = ''
def set_loghead(new_loghead):
    global loghead
    loghead = new_loghead.rstrip(': ') + ': '
    sys.excepthook = custom_excepthook
def log(*args, **kwargs):
    new_args = args
    if loghead: new_args = ( loghead,  *args)
    print(*new_args, **kwargs)
def log_warn(*args, **kwargs):
    if 'file' not in kwargs: kwargs['file'] = sys.stderr
    log('WARNING: ',  *args, **kwargs)

class EnhancedFalse:
    def __str__(self):
        raise Exception(loghead + "Script tries to stringify FALSE")
    def __repr__(self):
        raise Exception(loghead + "Script tries to stringify FALSE")
    def __bool__(self):
        return False
FALSE = EnhancedFalse()


class EnhancedDictTempl(dict):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, value in self.items():
            if isinstance(value, dict) and not isinstance(value, type(self)):
                self[key] = type(self)(value)
            elif isinstance(value, list):
                self[key] = self._convert_list(value)
    def _convert_list(self, lst):
        new_list = []
        for item in lst:
            if isinstance(item, dict) and not isinstance(item, type(self)):
                new_list.append(type(self)(item))
            elif isinstance(item, list):
                new_list.append(self._convert_list(item))
            else: new_list.append(item)
        return new_list
    def __setattr__(self, name, value):
        self[name] = value
    def __delattr__(self, name):
        try: del self[name]
        except KeyError: pass
    def __setitem__(self, key, value):
        processed_value = value
        if isinstance(value, dict) and not isinstance(value, type(self)):
            processed_value = type(self)(value)
        elif isinstance(value, list):
             processed_value = self._convert_list(value)
        super().__setitem__(key, processed_value)
class Dict(EnhancedDictTempl):
    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)
        try: return self[name]
        except :
            raise
class DictFALSE(EnhancedDictTempl):
    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"): raise AttributeError(name)
        try: return self[name]
        except KeyError:
            return FALSE
    def __getitem__(self, key):
        try: return super().__getitem__(key)
        except KeyError:
            return FALSE
class DictNone(EnhancedDictTempl):
    def __getattr__(self, name):
        if name.startswith("__") and name.endswith("__"):
            raise AttributeError(name)
        try: return self[name]
        except :
            return None
    def __getitem__(self, key):
        try: return super().__getitem__(key)
        except KeyError:
            return None
D = Dict # 试图访问不存在的键时, 报错
d = DictFALSE # 试图访问不存在的键时，会返回EnhancedFalse
dn = DictNone #试图访问不存在的键时， 返回None

# ================================================

scriptfilepath = os.path.abspath(__file__)
scriptdirpath = os.path.dirname(scriptfilepath)
scriptpadirpath = os.path.dirname(scriptdirpath)


main()
